# This is a basic workflow to help you get started with Actions

name: CI (macOS)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest

    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: Determine stack resolver
      run: |
        STACK_RESOLVER=$(yq .resolver stack.yaml)
        echo STACK_RESOLVER="${STACK_RESOLVER}" >> "${GITHUB_ENV}"

    # things to be restored:
    # Include STACK_RESOLVER in cache key, otherwise caches accumulate build products for different resolvers.

    - name: 💾 Restore cached stack global package db
      id:   stack-global
      uses: actions/cache/restore@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-global-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-global

    - name: 💾 Restore stack-installed programs in ~/.local/bin
      id:   stack-programs
      uses: actions/cache/restore@v3
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-work-${{ hashFiles('**.yaml') }}
        restore-keys: |
            ${{ runner.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-work
       
    - name: 💾 Restore cached .stack-work
      id:   stack-work
      uses: actions/cache/restore@v3
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-work-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-resolver-${{ env.STACK_RESOLVER }}-work

    # actions:

    - name: ⏬ Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: ⏬ Install stack
      run: |
        mkdir -p ~/.local/bin
        export PATH=~/.local/bin:$PATH        
        # brew install gnu-tar; curl -sL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack
        if [[ ! -x ~/.local/bin/stack ]]; then brew install gnu-tar; curl -sL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
        stack --version

    - name: ⏬ Install Agda
      run: stack install --resolver lts-20.26 Agda-2.6.4

    - name: ⏬ Install NPM Dependencies
      run: npm install
      
    - name: 🔨 Build stuff 
      run: npm run build
      
    - name: 🚗 Run tests
      run: | 
        # adding $(stack path --local-bin) to the PATH 
        PATH=$(stack path --local-bin):$PATH
        which agda
        
        npm test