# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    # things to be cached/restored:

    - name: 💾 Cache stack global package db
      id:   stack-global
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-after20210110-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-global-after202110110

    - name: 💾 Cache stack-installed programs in ~/.local/bin
      id:   stack-programs
      uses: actions/cache@v2
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-stack-programs-${{ hashFiles('**.yaml') }}
        restore-keys: |
             ${{ runner.os }}-stack-programs

    # actions:

    - name: ⏬ Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: ⏬ Install stack (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p ~/.local/bin
        export PATH=~/.local/bin:$PATH        
        # brew install gnu-tar; curl -sL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack
        if [[ ! -x ~/.local/bin/stack ]]; then brew install gnu-tar; curl -sL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; chmod a+x ~/.local/bin/stack; fi
        stack --version


    - name: ⏬ Install stack (Windows)
      if: matrix.os == 'windows-latest'
      # this step is needed to get stack.exe into PATH, for now
      run: |
        curl -sL https://get.haskellstack.org/stable/windows-x86_64.zip -o stack.zip
        7z x stack.zip stack.exe
        which stack
        stack --version
        which ./stack
        ./stack --version
      # must avoid GHC versions broken on windows such as 8.8.3 with https://gitlab.haskell.org/ghc/ghc/issues/17926
      # current default stack.yaml uses GHC 8.8.4 which hopefully is ok

    - name: ⏬ Install Agda (macOS)
      if: matrix.os == 'macos-latest'
      run: stack install Agda-2.6.2

    - name: ⏬ Install Agda (Windows)
      if: matrix.os == 'windows-latest'
      run: stack install Agda-2.6.2

    - name: ⏬ Install NPM Dependencies
      run: npm install
      
    - name: 🔨 Build stuff 
      run: npm run build
      
    - name: 🚗 Run tests (macOS)
      if: matrix.os == 'macos-latest'
      run: | 
        # adding $(stack path --local-bin) to the PATH 
        PATH=$(stack path --local-bin):$PATH
        which agda
        
        npm test

    - name: 🚗 Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: | 
        # adding (stack path --local-bin) to the PATH 
        set PATH=%PATH%;(stack path --local-bin)
        which agda

        npm test
